# Generated by Django 4.2.7 on 2023-12-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_discount_tax_alter_item_price_order_discounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='shop.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='shop.tax'),
        ),
    ]
