# Generated by Django 4.2.7 on 2023-12-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_discounts_alter_order_taxes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tax',
            new_name='Taxes',
        ),
    ]
