# Generated by Django 4.2.7 on 2023-12-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_tax_taxes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taxes',
            new_name='Tax',
        ),
    ]
